export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const CLEAR_RESTAURANT = 'CLEAR_RESTAURANT';
export const DELETE_SELECTED_RESTAURANTS = 'DELETE_SELECTED_RESTAURANTS';